---
- hosts: ipa:ldap:client
  roles:
  - packages
  - common
  vars_files:
  - variables.yml

- hosts: ad:ad-child
  gather_facts: no
  roles:
  - win-common
  vars_files:
  - variables.yml

- hosts: ad
  gather_facts: no
  roles:
  - win-forest
  vars_files:
  - variables.yml

- hosts: ipa
  gather_facts: no
  roles:
  - ipa
  vars_files:
  - variables.yml

- hosts: ad-child
  gather_facts: no
  roles:
  - win-domain
  vars_files:
  - variables.yml

- hosts: ldap:client
  gather_facts: no
  roles:
  - dnsclient
  vars_files:
  - variables.yml

- hosts: ldap
  gather_facts: no
  roles:
  - ldap
  vars_files:
  - variables.yml
  
- import_playbook: enroll.yml
