---
- hosts: ipa:ldap:client
  roles:
  - packages
  - common
  - reboot
  vars_files:
  - variables.yml

- hosts: ad:ad-child
  gather_facts: no
  roles:
  - win-common
  vars_files:
  - variables.yml

- hosts: ad
  gather_facts: yes
  roles:
  - win-forest
  - role: win-schema
    suffix: '{{ ad.suffix }}'
  - role: win-dns
    domain: '{{ ad.domain }}'
    hostname: '{{ ad.hostname }}'
  - role: win-users
    domain: '{{ ad.domain }}'
  vars_files:
  - variables.yml

- hosts: ipa
  gather_facts: no
  roles:
  - ipa
  vars_files:
  - variables.yml

- hosts: ad-child
  gather_facts: yes
  roles:
  - win-domain
  - role: win-dns
    domain: '{{ ad_child.domain }}'
    hostname: '{{ ad_child.hostname }}'
  - role: win-users
    domain: '{{ ad_child.domain }}'
  vars_files:
  - variables.yml

- hosts: ldap:client
  gather_facts: no
  roles:
  - dnsclient
  vars_files:
  - variables.yml

- hosts: ldap
  gather_facts: no
  roles:
  - ldap
  vars_files:
  - variables.yml
