- name: Python interpreter
  debug:
    msg: '{{ discovered_interpreter_python }} ({{ ansible_python_version }})'

#- name: Check if python3 is installed
#  raw: which python3
#  register: result
#  failed_when: False
#  changed_when: False
#
#- name: Make sure python3 is installed
#  become: True
#  raw: |
#    if which dnf &> /dev/null; then
#      dnf install -y python3
#    elif which yum &> /dev/null; then
#      yum install -y python3
#    fi
#  when: result.rc != 0
