- name: 'Create /shared/enrollment/{{ inventory_hostname }} directory'
  become: True
  file:
    path: '/shared/enrollment/{{ inventory_hostname }}/'
    state: directory

- name: Copy certificate to shared folder
  become: True
  copy:
    src: /etc/dirsrv/slapd-localhost/ca.crt
    dest: '/shared/enrollment/{{ inventory_hostname }}/'
    remote_src: yes
