export VAGRANT="yes"

# Source git bash-completion
if [ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]; then
  . /usr/share/git-core/contrib/completion/git-prompt.sh
fi

# Source additional scripts
INCLUDE_DIR="/shared/scripts"
if [ -d $INCLUDE_DIR ]; then
  INCLUDE_FILES=`find $INCLUDE_DIR -type f -name '*.sh' -printf '%d\t%p\n' | sort -nk1 | cut -f2-`
    
  for SCRIPT in $INCLUDE_FILES ; do
    if [ -f $SCRIPT ]; then
      . $SCRIPT
    fi
  done
fi
