export VAGRANT="yes"

# Source user's bashrc is available
if [ ! -z "$SSSD_TEST_SUITE_BASHRC" ]; then
    if [ -f "$SSSD_TEST_SUITE_BASHRC" ]; then
        . $SSSD_TEST_SUITE_BASHRC
        return
    fi
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Source git bash-completion
if [ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]; then
    . /usr/share/git-core/contrib/completion/git-prompt.sh
    GIT_PS1_SHOWDIRTYSTATE="yes"
    GIT_PS1_SHOWUNTRACKEDFILES="yes"
    _GIT_PROMPT='$(__git_ps1 " (%s)")'
fi

if [[ $EUID -eq 0 ]]; then
    export PS1="[\u@\H \w$_GIT_PROMPT]# "
else
    export PS1="[\u@\H \w$_GIT_PROMPT]\$ "
fi
