- name: SELinux is enabled in Fedora
  set_fact:
    selinux_enabled: true

- name: Install common packages
  become: True
  dnf:
    state: present
    name:
    - authselect
    - bash-completion
    - dbus-daemon
    - dbus-tools
    - dnsmasq
    - gdb
    - git
    - ldb-tools
    - libselinux-python3
    - mc
    - NetworkManager
    - openldap-clients
    - python3-pip
    - screen
    - systemtap
    - tig
    - tmate
    - tmux
    - valgrind
    - vim
    - wget

- name: Install IPA specific packages
  become: True
  dnf:
    state: present
    name:
    - freeipa-server
    - freeipa-server-dns
    - freeipa-server-trust-ad
  when: inventory_hostname == 'ipa'

- name: Install LDAP specific packages
  become: True
  dnf:
    state: present
    name:
    - 389-ds-base
  when: inventory_hostname == 'ldap'

- name: Install Client specific packages
  become: True
  dnf:
    state: present
    name:
    - adcli
    - autoconf
    - automake
    - bind-utils
    - c-ares-devel
    - check
    - check-devel
    - cifs-utils-devel
    - dbus-devel
    - dbus-libs
    - diffstat
    - docbook-style-xsl
    - doxygen
    - fakeroot
    - findutils
    - freeipa-client
    - gcc
    - gdm-pam-extensions-devel
    - gettext
    - gettext-devel
    - glib2-devel
    - gnutls-utils
    - http-parser-devel
    - jansson-devel
    - keyutils-libs-devel
    - krb5-devel
    - krb5-server
    - libcmocka
    - libcmocka-devel
    - libcollection-devel
    - libcurl-devel
    - libdhash-devel
    - libfaketime
    - libini_config-devel
    - libldb
    - libldb-devel
    - libnfsidmap-devel
    - libnl3-devel
    - libpath_utils-devel
    - libref_array-devel
    - libselinux-devel
    - libsemanage-devel
    - libsmbclient-devel
    - libtalloc
    - libtalloc-devel
    - libtdb
    - libtdb-devel
    - libtevent
    - libtevent-devel
    - libtool
    - libunistring-devel
    - libuuid-devel
    - libxml2
    - libxslt
    - m4
    - nspr-devel
    - nss-devel
    - nss-tools
    - nss-util-devel
    - nss_wrapper
    - oddjob
    - oddjob-mkhomedir
    - openldap-devel
    - openssh
    - openssl
    - openssl-devel
    - p11-kit-devel
    - pam-devel
    - pam_wrapper
    - pcre-devel
    - pcre2-devel
    - pkgconfig
    - po4a
    - popt-devel
    - python3-dbus
    - python3-devel
    - python3-requests
    - realmd
    - resolv_wrapper
    - samba-common-tools
    - samba-devel
    - samba-winbind
    - samba4-devel
    - selinux-policy-targeted
    - socket_wrapper
    - softhsm
    - sssd
    - sssd-*
    - systemd
    - systemd-devel
    - systemtap-sdt-devel
    - uid_wrapper
  when: inventory_hostname == 'client' or inventory_hostname == 'ipa'

- name: Install Client specific packages required for integration tests
  become: True
  dnf:
    state: present
    name:
    - clang-analyzer
    - curl-devel
    - fakeroot
    - http-parser-devel
    - krb5-server
    - krb5-workstation
    - lcov
    - libcmocka-devel
    - libfaketime
    - mock
    - nss_wrapper
    - openldap-clients
    - openldap-servers
    - pam_wrapper
    - python3-ldap
    - python3-ldb
    - python3-psutil
    - python3-pycodestyle
    - python3-pytest
    - python3-requests
    - redhat-lsb-core
    - rpm-build
    - uid_wrapper
    - valgrind
  when: inventory_hostname == 'client' or inventory_hostname == 'ipa'

- name: Install debug information for specific packages
  become: True
  shell: |
    dnf debuginfo-install -y  \
      authselect              \
      authselect-libs         \
      dbus                    \
      libcmocka               \
      libdhash                \
      libini_config           \
      libldb                  \
      libtalloc               \
      libtevent
  when: inventory_hostname == 'client' or inventory_hostname == 'ipa'
