- name: 'Create /shared/enrollment/{{ inventory_hostname }} directory'
  become: True
  file:
    path: '/shared/enrollment/{{ inventory_hostname }}/'
    state: directory

- include_tasks: 'ipa.yml'
  tags:
  - enroll-all
  - enroll-ipa

- include_tasks: 'ad.yml'
  tags:
  - enroll-all
  - enroll-ad

- include_tasks: 'ad-child.yml'
  tags:
  - enroll-all
  - enroll-ad-child

- name: Create /etc/sssd/sssd.conf
  become: True
  template:
    src: sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  register: client_configuration

- name: Create /etc/sudo.conf
  become: True
  template:
    src: sudo.conf
    dest: /etc/sudo.conf
    owner: root
    group: root
    mode: 0644

- name: Restart SSSD
  become: True
  service:
    name: sssd.service
    enabled: yes
    state: restarted
  when: client_configuration.changed
