- name: Create /root/localhost.inf
  become: True
  template:
    src: instance.inf
    dest: /root/localhost.inf
    owner: root
    group: root
    mode: 0600

- name: Create directory server instance
  become: True
  shell: |
    dscreate from-file /root/localhost.inf
  register: installed
  args:
    creates: '/etc/dirsrv/slapd-localhost'

