- name: Create /etc/NetworkManager/conf.d/enable_dnsmasq.conf
  become: True
  template:
    src: enable_dnsmasq.conf
    dest: /etc/NetworkManager/conf.d/enable_dnsmasq.conf
    owner: root
    group: root
    mode: 0644

- name: Create /etc/NetworkManager/dnsmasq.d/zone_vm.dnsmasq
  become: True
  template:
    src: zone_vm.dnsmasq
    dest: /etc/NetworkManager/dnsmasq.d/zone_vm.dnsmasq
    owner: root
    group: root
    mode: 0644
  register: result

- name: Start NetworkManager
  become: True
  service:
    name: NetworkManager.service
    enabled: yes
    state: started

- name: Reload NetworkManager configuration
  become: True
  shell: |
    nmcli con reload
  args:
    warn: False
  when: result.changed
